<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="77304" started-at="2019-04-08T16:31:15Z" finished-at="2019-04-08T16:32:32Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="77304" started-at="2019-04-08T16:31:15Z" finished-at="2019-04-08T16:32:32Z">
      <class name="SelPractice.excelUnlock">
        <test-method status="FAIL" signature="readCreds()[pri:0, instance:SelPractice.excelUnlock@34b7ac2f]" name="readCreds" duration-ms="77268" started-at="2019-04-08T22:01:15Z" finished-at="2019-04-08T22:02:32Z">
          <exception class="java.io.FileNotFoundException">
            <message>
              <![CDATA[D:\Kiran\ABL_ReagentPreparation_Column_Arrangement.xlsx (The process cannot access the file because it is being used by another process)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.FileNotFoundException: D:\Kiran\ABL_ReagentPreparation_Column_Arrangement.xlsx (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at org.apache.poi.openxml4j.opc.internal.FileHelper.copyFile(FileHelper.java:68)
	at org.apache.poi.openxml4j.opc.ZipPackage.closeImpl(ZipPackage.java:456)
	at org.apache.poi.openxml4j.opc.OPCPackage.close(OPCPackage.java:479)
	at org.apache.poi.POIXMLDocument.close(POIXMLDocument.java:189)
	at SelPractice.excelUnlock.readCreds(excelUnlock.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.FileNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readCreds -->
      </class> <!-- SelPractice.excelUnlock -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
